<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class Form2
    Inherits System.Windows.Forms.Form

    'Form overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()> _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing AndAlso components IsNot Nothing Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.  
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()> _
    Private Sub InitializeComponent()
        Me.components = New System.ComponentModel.Container()
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(Form2))
        Dim ControlBackground1 As Mitov.BasicLab.ControlBackground = New Mitov.BasicLab.ControlBackground()
        Dim ThermometerBevel1 As Mitov.InstrumentLab.ThermometerBevel = New Mitov.InstrumentLab.ThermometerBevel()
        Dim ElementSize1 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim VerticalCaption1 As Mitov.BasicLab.VerticalCaption = New Mitov.BasicLab.VerticalCaption()
        Dim ControlFont1 As Mitov.BasicLab.ControlFont = New Mitov.BasicLab.ControlFont()
        Dim GpBrush1 As Mitov.BasicLab.GPBrush = New Mitov.BasicLab.GPBrush()
        Dim GpBlend1 As Mitov.BasicLab.GPBlend = New Mitov.BasicLab.GPBlend()
        Dim GpBlends1 As Mitov.BasicLab.GPBlends = New Mitov.BasicLab.GPBlends()
        Dim GpBlendShape1 As Mitov.BasicLab.GPBlendShape = New Mitov.BasicLab.GPBlendShape()
        Dim GpGradient1 As Mitov.BasicLab.GPGradient = New Mitov.BasicLab.GPGradient()
        Dim GpCenterColor1 As Mitov.BasicLab.GPCenterColor = New Mitov.BasicLab.GPCenterColor()
        Dim GpCenterPoint1 As Mitov.BasicLab.GPCenterPoint = New Mitov.BasicLab.GPCenterPoint()
        Dim GpColors1 As Mitov.BasicLab.GPColors = New Mitov.BasicLab.GPColors()
        Dim GpPoints1 As Mitov.BasicLab.GPPoints = New Mitov.BasicLab.GPPoints()
        Dim GpHatch1 As Mitov.BasicLab.GPHatch = New Mitov.BasicLab.GPHatch()
        Dim GpInterpolationColors1 As Mitov.BasicLab.GPInterpolationColors = New Mitov.BasicLab.GPInterpolationColors()
        Dim GpOptionalMultiPen1 As Mitov.BasicLab.GPOptionalMultiPen = New Mitov.BasicLab.GPOptionalMultiPen()
        Dim GpBrush2 As Mitov.BasicLab.GPBrush = New Mitov.BasicLab.GPBrush()
        Dim GpBlend2 As Mitov.BasicLab.GPBlend = New Mitov.BasicLab.GPBlend()
        Dim GpBlends2 As Mitov.BasicLab.GPBlends = New Mitov.BasicLab.GPBlends()
        Dim GpBlendShape2 As Mitov.BasicLab.GPBlendShape = New Mitov.BasicLab.GPBlendShape()
        Dim GpGradient2 As Mitov.BasicLab.GPGradient = New Mitov.BasicLab.GPGradient()
        Dim GpCenterColor2 As Mitov.BasicLab.GPCenterColor = New Mitov.BasicLab.GPCenterColor()
        Dim GpCenterPoint2 As Mitov.BasicLab.GPCenterPoint = New Mitov.BasicLab.GPCenterPoint()
        Dim GpColors2 As Mitov.BasicLab.GPColors = New Mitov.BasicLab.GPColors()
        Dim GpPoints2 As Mitov.BasicLab.GPPoints = New Mitov.BasicLab.GPPoints()
        Dim GpHatch2 As Mitov.BasicLab.GPHatch = New Mitov.BasicLab.GPHatch()
        Dim GpInterpolationColors2 As Mitov.BasicLab.GPInterpolationColors = New Mitov.BasicLab.GPInterpolationColors()
        Dim GpPenCompound1 As Mitov.BasicLab.GPPenCompound = New Mitov.BasicLab.GPPenCompound()
        Dim GpDashStyle1 As Mitov.BasicLab.GPDashStyle = New Mitov.BasicLab.GPDashStyle()
        Dim GpCustomDash1 As Mitov.BasicLab.GPCustomDash = New Mitov.BasicLab.GPCustomDash()
        Dim ElementSize2 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim ElementOffsets1 As Mitov.BasicLab.ElementOffsets = New Mitov.BasicLab.ElementOffsets()
        Dim ElementOffsetSize1 As Mitov.BasicLab.ElementOffsetSize = New Mitov.BasicLab.ElementOffsetSize()
        Dim ElementOffsetSize2 As Mitov.BasicLab.ElementOffsetSize = New Mitov.BasicLab.ElementOffsetSize()
        Dim ThermometerIndicator1 As Mitov.InstrumentLab.ThermometerIndicator = New Mitov.InstrumentLab.ThermometerIndicator()
        Dim ThermometerReservoir1 As Mitov.InstrumentLab.ThermometerReservoir = New Mitov.InstrumentLab.ThermometerReservoir()
        Dim ElementSize3 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim ElementSize4 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim SinkPin1 As OpenWire.Proxy.SinkPin = New OpenWire.Proxy.SinkPin()
        Dim AnalogGaugeScaleRanges1 As Mitov.InstrumentLab.AnalogGaugeScaleRanges = New Mitov.InstrumentLab.AnalogGaugeScaleRanges()
        Dim ElementSize5 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim ElementSize6 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim Rotation1 As Mitov.InstrumentLab.Rotation = New Mitov.InstrumentLab.Rotation()
        Dim BasicGaugeScale1 As Mitov.InstrumentLab.BasicGaugeScale = New Mitov.InstrumentLab.BasicGaugeScale()
        Dim InstrumentMajorTicks1 As Mitov.InstrumentLab.InstrumentMajorTicks = New Mitov.InstrumentLab.InstrumentMajorTicks()
        Dim GpBrush3 As Mitov.BasicLab.GPBrush = New Mitov.BasicLab.GPBrush()
        Dim GpBlend3 As Mitov.BasicLab.GPBlend = New Mitov.BasicLab.GPBlend()
        Dim GpBlends3 As Mitov.BasicLab.GPBlends = New Mitov.BasicLab.GPBlends()
        Dim GpBlendShape3 As Mitov.BasicLab.GPBlendShape = New Mitov.BasicLab.GPBlendShape()
        Dim GpGradient3 As Mitov.BasicLab.GPGradient = New Mitov.BasicLab.GPGradient()
        Dim GpCenterColor3 As Mitov.BasicLab.GPCenterColor = New Mitov.BasicLab.GPCenterColor()
        Dim GpCenterPoint3 As Mitov.BasicLab.GPCenterPoint = New Mitov.BasicLab.GPCenterPoint()
        Dim GpColors3 As Mitov.BasicLab.GPColors = New Mitov.BasicLab.GPColors()
        Dim GpPoints3 As Mitov.BasicLab.GPPoints = New Mitov.BasicLab.GPPoints()
        Dim GpHatch3 As Mitov.BasicLab.GPHatch = New Mitov.BasicLab.GPHatch()
        Dim GpInterpolationColors3 As Mitov.BasicLab.GPInterpolationColors = New Mitov.BasicLab.GPInterpolationColors()
        Dim InstrumentTicksText1 As Mitov.InstrumentLab.InstrumentTicksText = New Mitov.InstrumentLab.InstrumentTicksText()
        Dim ControlFont2 As Mitov.BasicLab.ControlFont = New Mitov.BasicLab.ControlFont()
        Dim GpBrush4 As Mitov.BasicLab.GPBrush = New Mitov.BasicLab.GPBrush()
        Dim GpBlend4 As Mitov.BasicLab.GPBlend = New Mitov.BasicLab.GPBlend()
        Dim GpBlends4 As Mitov.BasicLab.GPBlends = New Mitov.BasicLab.GPBlends()
        Dim GpBlendShape4 As Mitov.BasicLab.GPBlendShape = New Mitov.BasicLab.GPBlendShape()
        Dim GpGradient4 As Mitov.BasicLab.GPGradient = New Mitov.BasicLab.GPGradient()
        Dim GpCenterColor4 As Mitov.BasicLab.GPCenterColor = New Mitov.BasicLab.GPCenterColor()
        Dim GpCenterPoint4 As Mitov.BasicLab.GPCenterPoint = New Mitov.BasicLab.GPCenterPoint()
        Dim GpColors4 As Mitov.BasicLab.GPColors = New Mitov.BasicLab.GPColors()
        Dim GpPoints4 As Mitov.BasicLab.GPPoints = New Mitov.BasicLab.GPPoints()
        Dim GpHatch4 As Mitov.BasicLab.GPHatch = New Mitov.BasicLab.GPHatch()
        Dim GpInterpolationColors4 As Mitov.BasicLab.GPInterpolationColors = New Mitov.BasicLab.GPInterpolationColors()
        Dim GpOptionalMultiPen2 As Mitov.BasicLab.GPOptionalMultiPen = New Mitov.BasicLab.GPOptionalMultiPen()
        Dim GpBrush5 As Mitov.BasicLab.GPBrush = New Mitov.BasicLab.GPBrush()
        Dim GpBlend5 As Mitov.BasicLab.GPBlend = New Mitov.BasicLab.GPBlend()
        Dim GpBlends5 As Mitov.BasicLab.GPBlends = New Mitov.BasicLab.GPBlends()
        Dim GpBlendShape5 As Mitov.BasicLab.GPBlendShape = New Mitov.BasicLab.GPBlendShape()
        Dim GpGradient5 As Mitov.BasicLab.GPGradient = New Mitov.BasicLab.GPGradient()
        Dim GpCenterColor5 As Mitov.BasicLab.GPCenterColor = New Mitov.BasicLab.GPCenterColor()
        Dim GpCenterPoint5 As Mitov.BasicLab.GPCenterPoint = New Mitov.BasicLab.GPCenterPoint()
        Dim GpColors5 As Mitov.BasicLab.GPColors = New Mitov.BasicLab.GPColors()
        Dim GpPoints5 As Mitov.BasicLab.GPPoints = New Mitov.BasicLab.GPPoints()
        Dim GpHatch5 As Mitov.BasicLab.GPHatch = New Mitov.BasicLab.GPHatch()
        Dim GpInterpolationColors5 As Mitov.BasicLab.GPInterpolationColors = New Mitov.BasicLab.GPInterpolationColors()
        Dim GpPenCompound2 As Mitov.BasicLab.GPPenCompound = New Mitov.BasicLab.GPPenCompound()
        Dim GpDashStyle2 As Mitov.BasicLab.GPDashStyle = New Mitov.BasicLab.GPDashStyle()
        Dim GpCustomDash2 As Mitov.BasicLab.GPCustomDash = New Mitov.BasicLab.GPCustomDash()
        Dim ElementSize7 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim ElementSize8 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim ElementSize9 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim InstrumentEndTick1 As Mitov.InstrumentLab.InstrumentEndTick = New Mitov.InstrumentLab.InstrumentEndTick()
        Dim OptionalInstrumentProperty1 As Mitov.BasicLab.OptionalInstrumentProperty = New Mitov.BasicLab.OptionalInstrumentProperty()
        Dim InstrumentEndTick2 As Mitov.InstrumentLab.InstrumentEndTick = New Mitov.InstrumentLab.InstrumentEndTick()
        Dim OptionalInstrumentProperty2 As Mitov.BasicLab.OptionalInstrumentProperty = New Mitov.BasicLab.OptionalInstrumentProperty()
        Dim ElementSize10 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim InstrumentLabeledTicks1 As Mitov.InstrumentLab.InstrumentLabeledTicks = New Mitov.InstrumentLab.InstrumentLabeledTicks()
        Dim GpBrush6 As Mitov.BasicLab.GPBrush = New Mitov.BasicLab.GPBrush()
        Dim GpBlend6 As Mitov.BasicLab.GPBlend = New Mitov.BasicLab.GPBlend()
        Dim GpBlends6 As Mitov.BasicLab.GPBlends = New Mitov.BasicLab.GPBlends()
        Dim GpBlendShape6 As Mitov.BasicLab.GPBlendShape = New Mitov.BasicLab.GPBlendShape()
        Dim GpGradient6 As Mitov.BasicLab.GPGradient = New Mitov.BasicLab.GPGradient()
        Dim GpCenterColor6 As Mitov.BasicLab.GPCenterColor = New Mitov.BasicLab.GPCenterColor()
        Dim GpCenterPoint6 As Mitov.BasicLab.GPCenterPoint = New Mitov.BasicLab.GPCenterPoint()
        Dim GpColors6 As Mitov.BasicLab.GPColors = New Mitov.BasicLab.GPColors()
        Dim GpPoints6 As Mitov.BasicLab.GPPoints = New Mitov.BasicLab.GPPoints()
        Dim GpHatch6 As Mitov.BasicLab.GPHatch = New Mitov.BasicLab.GPHatch()
        Dim GpInterpolationColors6 As Mitov.BasicLab.GPInterpolationColors = New Mitov.BasicLab.GPInterpolationColors()
        Dim InstrumentTicksText2 As Mitov.InstrumentLab.InstrumentTicksText = New Mitov.InstrumentLab.InstrumentTicksText()
        Dim ControlFont3 As Mitov.BasicLab.ControlFont = New Mitov.BasicLab.ControlFont()
        Dim GpBrush7 As Mitov.BasicLab.GPBrush = New Mitov.BasicLab.GPBrush()
        Dim GpBlend7 As Mitov.BasicLab.GPBlend = New Mitov.BasicLab.GPBlend()
        Dim GpBlends7 As Mitov.BasicLab.GPBlends = New Mitov.BasicLab.GPBlends()
        Dim GpBlendShape7 As Mitov.BasicLab.GPBlendShape = New Mitov.BasicLab.GPBlendShape()
        Dim GpGradient7 As Mitov.BasicLab.GPGradient = New Mitov.BasicLab.GPGradient()
        Dim GpCenterColor7 As Mitov.BasicLab.GPCenterColor = New Mitov.BasicLab.GPCenterColor()
        Dim GpCenterPoint7 As Mitov.BasicLab.GPCenterPoint = New Mitov.BasicLab.GPCenterPoint()
        Dim GpColors7 As Mitov.BasicLab.GPColors = New Mitov.BasicLab.GPColors()
        Dim GpPoints7 As Mitov.BasicLab.GPPoints = New Mitov.BasicLab.GPPoints()
        Dim GpHatch7 As Mitov.BasicLab.GPHatch = New Mitov.BasicLab.GPHatch()
        Dim GpInterpolationColors7 As Mitov.BasicLab.GPInterpolationColors = New Mitov.BasicLab.GPInterpolationColors()
        Dim GpOptionalMultiPen3 As Mitov.BasicLab.GPOptionalMultiPen = New Mitov.BasicLab.GPOptionalMultiPen()
        Dim GpBrush8 As Mitov.BasicLab.GPBrush = New Mitov.BasicLab.GPBrush()
        Dim GpBlend8 As Mitov.BasicLab.GPBlend = New Mitov.BasicLab.GPBlend()
        Dim GpBlends8 As Mitov.BasicLab.GPBlends = New Mitov.BasicLab.GPBlends()
        Dim GpBlendShape8 As Mitov.BasicLab.GPBlendShape = New Mitov.BasicLab.GPBlendShape()
        Dim GpGradient8 As Mitov.BasicLab.GPGradient = New Mitov.BasicLab.GPGradient()
        Dim GpCenterColor8 As Mitov.BasicLab.GPCenterColor = New Mitov.BasicLab.GPCenterColor()
        Dim GpCenterPoint8 As Mitov.BasicLab.GPCenterPoint = New Mitov.BasicLab.GPCenterPoint()
        Dim GpColors8 As Mitov.BasicLab.GPColors = New Mitov.BasicLab.GPColors()
        Dim GpPoints8 As Mitov.BasicLab.GPPoints = New Mitov.BasicLab.GPPoints()
        Dim GpHatch8 As Mitov.BasicLab.GPHatch = New Mitov.BasicLab.GPHatch()
        Dim GpInterpolationColors8 As Mitov.BasicLab.GPInterpolationColors = New Mitov.BasicLab.GPInterpolationColors()
        Dim GpPenCompound3 As Mitov.BasicLab.GPPenCompound = New Mitov.BasicLab.GPPenCompound()
        Dim GpDashStyle3 As Mitov.BasicLab.GPDashStyle = New Mitov.BasicLab.GPDashStyle()
        Dim GpCustomDash3 As Mitov.BasicLab.GPCustomDash = New Mitov.BasicLab.GPCustomDash()
        Dim ElementSize11 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim ElementSize12 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim ElementSize13 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim ElementSize14 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim ElementSize15 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim ScalePrecision1 As Mitov.InstrumentLab.ScalePrecision = New Mitov.InstrumentLab.ScalePrecision()
        Dim DecimalPointSegment1 As Mitov.InstrumentLab.DecimalPointSegment = New Mitov.InstrumentLab.DecimalPointSegment()
        Dim DecimalPointOffset1 As Mitov.InstrumentLab.DecimalPointOffset = New Mitov.InstrumentLab.DecimalPointOffset()
        Dim ElementSize16 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim ElementSize17 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim ElementSize18 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim SegmentIndents1 As Mitov.InstrumentLab.SegmentIndents = New Mitov.InstrumentLab.SegmentIndents()
        Dim ElementSize19 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim ElementSize20 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim ElementSize21 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim ElementSize22 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim SinkPin2 As OpenWire.Proxy.SinkPin = New OpenWire.Proxy.SinkPin()
        Dim Rotation2 As Mitov.InstrumentLab.Rotation = New Mitov.InstrumentLab.Rotation()
        Dim DigitalClockSections1 As Mitov.InstrumentLab.DigitalClockSections = New Mitov.InstrumentLab.DigitalClockSections()
        Dim DigitalAmPmSection1 As Mitov.InstrumentLab.DigitalAmPmSection = New Mitov.InstrumentLab.DigitalAmPmSection()
        Dim PointOffset1 As Mitov.InstrumentLab.PointOffset = New Mitov.InstrumentLab.PointOffset()
        Dim ElementSize23 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim ElementSize24 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim SegmentFont1 As Mitov.InstrumentLab.SegmentFont = New Mitov.InstrumentLab.SegmentFont()
        Dim ElementSize25 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim PointOffset2 As Mitov.InstrumentLab.PointOffset = New Mitov.InstrumentLab.PointOffset()
        Dim ElementSize26 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim ElementSize27 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim ElementSize28 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim DigitalHourSection1 As Mitov.InstrumentLab.DigitalHourSection = New Mitov.InstrumentLab.DigitalHourSection()
        Dim MillisecondsClockSection1 As Mitov.InstrumentLab.MillisecondsClockSection = New Mitov.InstrumentLab.MillisecondsClockSection()
        Dim SegmentClockSeparator1 As Mitov.InstrumentLab.SegmentClockSeparator = New Mitov.InstrumentLab.SegmentClockSeparator()
        Dim ElementSize29 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim DigitalClockSection1 As Mitov.InstrumentLab.DigitalClockSection = New Mitov.InstrumentLab.DigitalClockSection()
        Dim SegmentClockSeparator2 As Mitov.InstrumentLab.SegmentClockSeparator = New Mitov.InstrumentLab.SegmentClockSeparator()
        Dim ElementSize30 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim DigitalClockSection2 As Mitov.InstrumentLab.DigitalClockSection = New Mitov.InstrumentLab.DigitalClockSection()
        Dim SegmentClockSeparator3 As Mitov.InstrumentLab.SegmentClockSeparator = New Mitov.InstrumentLab.SegmentClockSeparator()
        Dim ElementSize31 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim Segment1 As Mitov.InstrumentLab.Segment = New Mitov.InstrumentLab.Segment()
        Dim ElementSize32 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim InactiveColor1 As Mitov.InstrumentLab.InactiveColor = New Mitov.InstrumentLab.InactiveColor()
        Dim ElementSize33 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim DecimalPointSegment2 As Mitov.InstrumentLab.DecimalPointSegment = New Mitov.InstrumentLab.DecimalPointSegment()
        Dim DecimalPointOffset2 As Mitov.InstrumentLab.DecimalPointOffset = New Mitov.InstrumentLab.DecimalPointOffset()
        Dim ElementSize34 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim ElementSize35 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim ElementSize36 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim SegmentIndents2 As Mitov.InstrumentLab.SegmentIndents = New Mitov.InstrumentLab.SegmentIndents()
        Dim ElementSize37 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim ElementSize38 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim ElementSize39 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim ElementSize40 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim SinkPin3 As OpenWire.Proxy.SinkPin = New OpenWire.Proxy.SinkPin()
        Dim Rotation3 As Mitov.InstrumentLab.Rotation = New Mitov.InstrumentLab.Rotation()
        Dim DigitalClockSections2 As Mitov.InstrumentLab.DigitalClockSections = New Mitov.InstrumentLab.DigitalClockSections()
        Dim DigitalAmPmSection2 As Mitov.InstrumentLab.DigitalAmPmSection = New Mitov.InstrumentLab.DigitalAmPmSection()
        Dim PointOffset3 As Mitov.InstrumentLab.PointOffset = New Mitov.InstrumentLab.PointOffset()
        Dim ElementSize41 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim ElementSize42 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim SegmentFont2 As Mitov.InstrumentLab.SegmentFont = New Mitov.InstrumentLab.SegmentFont()
        Dim ElementSize43 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim PointOffset4 As Mitov.InstrumentLab.PointOffset = New Mitov.InstrumentLab.PointOffset()
        Dim ElementSize44 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim ElementSize45 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim ElementSize46 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim DigitalHourSection2 As Mitov.InstrumentLab.DigitalHourSection = New Mitov.InstrumentLab.DigitalHourSection()
        Dim MillisecondsClockSection2 As Mitov.InstrumentLab.MillisecondsClockSection = New Mitov.InstrumentLab.MillisecondsClockSection()
        Dim SegmentClockSeparator4 As Mitov.InstrumentLab.SegmentClockSeparator = New Mitov.InstrumentLab.SegmentClockSeparator()
        Dim ElementSize47 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim DigitalClockSection3 As Mitov.InstrumentLab.DigitalClockSection = New Mitov.InstrumentLab.DigitalClockSection()
        Dim SegmentClockSeparator5 As Mitov.InstrumentLab.SegmentClockSeparator = New Mitov.InstrumentLab.SegmentClockSeparator()
        Dim ElementSize48 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim DigitalClockSection4 As Mitov.InstrumentLab.DigitalClockSection = New Mitov.InstrumentLab.DigitalClockSection()
        Dim SegmentClockSeparator6 As Mitov.InstrumentLab.SegmentClockSeparator = New Mitov.InstrumentLab.SegmentClockSeparator()
        Dim ElementSize49 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim Segment2 As Mitov.InstrumentLab.Segment = New Mitov.InstrumentLab.Segment()
        Dim ElementSize50 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Dim InactiveColor2 As Mitov.InstrumentLab.InactiveColor = New Mitov.InstrumentLab.InactiveColor()
        Dim ElementSize51 As Mitov.BasicLab.ElementSize = New Mitov.BasicLab.ElementSize()
        Me.Image1 = New Mitov.UserLab.Image(Me.components)
        Me.Button1 = New System.Windows.Forms.Button()
        Me.Button2 = New System.Windows.Forms.Button()
        Me.Thermometer1 = New Mitov.InstrumentLab.Thermometer(Me.components)
        Me.SegmentClock1 = New Mitov.InstrumentLab.SegmentClock(Me.components)
        Me.SegmentClock2 = New Mitov.InstrumentLab.SegmentClock(Me.components)
        CType(Me.Image1, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.Thermometer1, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.SegmentClock1, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.SegmentClock2, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SuspendLayout()
        '
        'Image1
        '
        Me.Image1.BackColor = System.Drawing.SystemColors.Control
        Me.Image1.InternalData = CType(resources.GetObject("Image1.InternalData"), Vcl.VclBinaryData)
        Me.Image1.Location = New System.Drawing.Point(12, 12)
        Me.Image1.Name = "Image1"
        Me.Image1.Size = New System.Drawing.Size(304, 278)
        Me.Image1.TabIndex = 0
        Me.Image1.Text = "Image1"
        '
        'Button1
        '
        Me.Button1.Font = New System.Drawing.Font("Microsoft Sans Serif", 15.75!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.Button1.Location = New System.Drawing.Point(21, 322)
        Me.Button1.Name = "Button1"
        Me.Button1.Size = New System.Drawing.Size(123, 30)
        Me.Button1.TabIndex = 1
        Me.Button1.Text = "Turn On"
        Me.Button1.UseVisualStyleBackColor = True
        '
        'Button2
        '
        Me.Button2.Font = New System.Drawing.Font("Microsoft Sans Serif", 15.75!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.Button2.Location = New System.Drawing.Point(168, 322)
        Me.Button2.Name = "Button2"
        Me.Button2.Size = New System.Drawing.Size(118, 30)
        Me.Button2.TabIndex = 2
        Me.Button2.Text = "Analyze"
        Me.Button2.UseVisualStyleBackColor = True
        '
        'Thermometer1
        '
        ControlBackground1.Color = System.Drawing.SystemColors.Control
        Me.Thermometer1.Background = ControlBackground1
        ThermometerBevel1.Color = System.Drawing.Color.FromArgb(CType(CType(211, Byte), Integer), CType(CType(211, Byte), Integer), CType(CType(211, Byte), Integer))
        ElementSize1.Value = 0.05!
        ThermometerBevel1.Width = ElementSize1
        Me.Thermometer1.Border = ThermometerBevel1
        VerticalCaption1.Angle = 90.0!
        GpBlend1.Blends = GpBlends1
        GpBlendShape1.Focus = 0.5!
        GpBlendShape1.Scale = 1.0!
        GpBlend1.Shape = GpBlendShape1
        GpBrush1.Blend = GpBlend1
        GpBrush1.Color = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer))
        GpCenterColor1.Color = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer))
        GpCenterPoint1.X = 0!
        GpCenterPoint1.Y = 0!
        GpCenterColor1.Point = GpCenterPoint1
        GpGradient1.CenterColor = GpCenterColor1
        GpGradient1.Colors = GpColors1
        GpGradient1.Path = GpPoints1
        GpBrush1.Gradient = GpGradient1
        GpHatch1.BackgroundColor = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer))
        GpHatch1.ForegroundColor = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer))
        GpBrush1.Hatch = GpHatch1
        GpBrush1.InterpolationColors = GpInterpolationColors1
        ControlFont1.Brush = GpBrush1
        ControlFont1.InternalData = CType(resources.GetObject("ControlFont1.InternalData"), Vcl.VclBinaryData)
        GpBlend2.Blends = GpBlends2
        GpBlendShape2.Focus = 0.5!
        GpBlendShape2.Scale = 1.0!
        GpBlend2.Shape = GpBlendShape2
        GpBrush2.Blend = GpBlend2
        GpBrush2.Color = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer))
        GpCenterColor2.Color = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer))
        GpCenterPoint2.X = 0!
        GpCenterPoint2.Y = 0!
        GpCenterColor2.Point = GpCenterPoint2
        GpGradient2.CenterColor = GpCenterColor2
        GpGradient2.Colors = GpColors2
        GpGradient2.Path = GpPoints2
        GpBrush2.Gradient = GpGradient2
        GpHatch2.BackgroundColor = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer))
        GpHatch2.ForegroundColor = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer))
        GpBrush2.Hatch = GpHatch2
        GpBrush2.InterpolationColors = GpInterpolationColors2
        GpOptionalMultiPen1.Brush = GpBrush2
        GpOptionalMultiPen1.Compound = GpPenCompound1
        GpDashStyle1.CustomDash = GpCustomDash1
        GpDashStyle1.Offset = 0!
        GpOptionalMultiPen1.DashStyle = GpDashStyle1
        GpOptionalMultiPen1.Enabled = False
        GpOptionalMultiPen1.MiterLimit = 0!
        GpOptionalMultiPen1.Width = 1.0!
        ControlFont1.Pen = GpOptionalMultiPen1
        ElementSize2.Value = 0.15!
        ControlFont1.Size = ElementSize2
        VerticalCaption1.Font = ControlFont1
        ElementOffsetSize1.Value = 0.8!
        ElementOffsets1.X = ElementOffsetSize1
        ElementOffsetSize2.Value = 0!
        ElementOffsets1.Y = ElementOffsetSize2
        VerticalCaption1.Position = ElementOffsets1
        Me.Thermometer1.Caption = VerticalCaption1
        ThermometerIndicator1.BackColor = System.Drawing.Color.FromArgb(CType(CType(128, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer))
        ThermometerIndicator1.Color = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer))
        ElementSize3.Value = 0.25!
        ThermometerReservoir1.Size = ElementSize3
        ThermometerIndicator1.Reservoir = ThermometerReservoir1
        ElementSize4.Value = 0.1!
        ThermometerIndicator1.Width = ElementSize4
        Me.Thermometer1.Indicator = ThermometerIndicator1
        Me.Thermometer1.InputPin = SinkPin1
        Me.Thermometer1.InternalData = CType(resources.GetObject("Thermometer1.InternalData"), Vcl.VclBinaryData)
        Me.Thermometer1.Location = New System.Drawing.Point(338, 12)
        Me.Thermometer1.Max = 100.0R
        Me.Thermometer1.Min = 0R
        Me.Thermometer1.Name = "Thermometer1"
        AnalogGaugeScaleRanges1.Color = System.Drawing.Color.FromArgb(CType(CType(128, Byte), Integer), CType(CType(128, Byte), Integer), CType(CType(128, Byte), Integer))
        ElementSize5.Value = 0.35!
        AnalogGaugeScaleRanges1.Position = ElementSize5
        ElementSize6.Value = 0.05!
        AnalogGaugeScaleRanges1.Width = ElementSize6
        Me.Thermometer1.Ranges = AnalogGaugeScaleRanges1
        Rotation1.Angle = 0!
        Rotation1.Width = 0.7!
        Me.Thermometer1.Rotation = Rotation1
        GpBlend3.Blends = GpBlends3
        GpBlendShape3.Focus = 0.5!
        GpBlendShape3.Scale = 1.0!
        GpBlend3.Shape = GpBlendShape3
        GpBrush3.Blend = GpBlend3
        GpBrush3.Color = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer))
        GpCenterColor3.Color = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer))
        GpCenterPoint3.X = 0!
        GpCenterPoint3.Y = 0!
        GpCenterColor3.Point = GpCenterPoint3
        GpGradient3.CenterColor = GpCenterColor3
        GpGradient3.Colors = GpColors3
        GpGradient3.Path = GpPoints3
        GpBrush3.Gradient = GpGradient3
        GpHatch3.BackgroundColor = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer))
        GpHatch3.ForegroundColor = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer))
        GpBrush3.Hatch = GpHatch3
        GpBrush3.InterpolationColors = GpInterpolationColors3
        InstrumentMajorTicks1.Brush = GpBrush3
        InstrumentMajorTicks1.Count = CType(11UI, UInteger)
        InstrumentTicksText1.Angle = 0!
        GpBlend4.Blends = GpBlends4
        GpBlendShape4.Focus = 0.5!
        GpBlendShape4.Scale = 1.0!
        GpBlend4.Shape = GpBlendShape4
        GpBrush4.Blend = GpBlend4
        GpBrush4.Color = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer))
        GpCenterColor4.Color = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer))
        GpCenterPoint4.X = 0!
        GpCenterPoint4.Y = 0!
        GpCenterColor4.Point = GpCenterPoint4
        GpGradient4.CenterColor = GpCenterColor4
        GpGradient4.Colors = GpColors4
        GpGradient4.Path = GpPoints4
        GpBrush4.Gradient = GpGradient4
        GpHatch4.BackgroundColor = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer))
        GpHatch4.ForegroundColor = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer))
        GpBrush4.Hatch = GpHatch4
        GpBrush4.InterpolationColors = GpInterpolationColors4
        ControlFont2.Brush = GpBrush4
        ControlFont2.InternalData = CType(resources.GetObject("ControlFont2.InternalData"), Vcl.VclBinaryData)
        GpBlend5.Blends = GpBlends5
        GpBlendShape5.Focus = 0.5!
        GpBlendShape5.Scale = 1.0!
        GpBlend5.Shape = GpBlendShape5
        GpBrush5.Blend = GpBlend5
        GpBrush5.Color = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer))
        GpCenterColor5.Color = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer))
        GpCenterPoint5.X = 0!
        GpCenterPoint5.Y = 0!
        GpCenterColor5.Point = GpCenterPoint5
        GpGradient5.CenterColor = GpCenterColor5
        GpGradient5.Colors = GpColors5
        GpGradient5.Path = GpPoints5
        GpBrush5.Gradient = GpGradient5
        GpHatch5.BackgroundColor = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer))
        GpHatch5.ForegroundColor = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer))
        GpBrush5.Hatch = GpHatch5
        GpBrush5.InterpolationColors = GpInterpolationColors5
        GpOptionalMultiPen2.Brush = GpBrush5
        GpOptionalMultiPen2.Compound = GpPenCompound2
        GpDashStyle2.CustomDash = GpCustomDash2
        GpDashStyle2.Offset = 0!
        GpOptionalMultiPen2.DashStyle = GpDashStyle2
        GpOptionalMultiPen2.Enabled = False
        GpOptionalMultiPen2.MiterLimit = 0!
        GpOptionalMultiPen2.Width = 1.0!
        ControlFont2.Pen = GpOptionalMultiPen2
        ElementSize7.Value = 0.09!
        ControlFont2.Size = ElementSize7
        InstrumentTicksText1.Font = ControlFont2
        ElementSize8.Value = 0.42!
        InstrumentTicksText1.Position = ElementSize8
        InstrumentTicksText1.Visible = True
        InstrumentMajorTicks1.Labels = InstrumentTicksText1
        ElementSize9.Value = 0.25!
        InstrumentMajorTicks1.Length = ElementSize9
        OptionalInstrumentProperty1.Visible = True
        InstrumentEndTick1.TickLabel = OptionalInstrumentProperty1
        InstrumentEndTick1.Visible = True
        InstrumentMajorTicks1.MaxTick = InstrumentEndTick1
        OptionalInstrumentProperty2.Visible = True
        InstrumentEndTick2.TickLabel = OptionalInstrumentProperty2
        InstrumentEndTick2.Visible = True
        InstrumentMajorTicks1.MinTick = InstrumentEndTick2
        ElementSize10.Value = 0.01!
        InstrumentMajorTicks1.Thickness = ElementSize10
        InstrumentMajorTicks1.Visible = True
        BasicGaugeScale1.MajorTicks = InstrumentMajorTicks1
        GpBlend6.Blends = GpBlends6
        GpBlendShape6.Focus = 0.5!
        GpBlendShape6.Scale = 1.0!
        GpBlend6.Shape = GpBlendShape6
        GpBrush6.Blend = GpBlend6
        GpBrush6.Color = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer))
        GpCenterColor6.Color = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer))
        GpCenterPoint6.X = 0!
        GpCenterPoint6.Y = 0!
        GpCenterColor6.Point = GpCenterPoint6
        GpGradient6.CenterColor = GpCenterColor6
        GpGradient6.Colors = GpColors6
        GpGradient6.Path = GpPoints6
        GpBrush6.Gradient = GpGradient6
        GpHatch6.BackgroundColor = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer))
        GpHatch6.ForegroundColor = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer))
        GpBrush6.Hatch = GpHatch6
        GpBrush6.InterpolationColors = GpInterpolationColors6
        InstrumentLabeledTicks1.Brush = GpBrush6
        InstrumentLabeledTicks1.Count = CType(4UI, UInteger)
        InstrumentTicksText2.Angle = 0!
        GpBlend7.Blends = GpBlends7
        GpBlendShape7.Focus = 0.5!
        GpBlendShape7.Scale = 1.0!
        GpBlend7.Shape = GpBlendShape7
        GpBrush7.Blend = GpBlend7
        GpBrush7.Color = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer))
        GpCenterColor7.Color = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer))
        GpCenterPoint7.X = 0!
        GpCenterPoint7.Y = 0!
        GpCenterColor7.Point = GpCenterPoint7
        GpGradient7.CenterColor = GpCenterColor7
        GpGradient7.Colors = GpColors7
        GpGradient7.Path = GpPoints7
        GpBrush7.Gradient = GpGradient7
        GpHatch7.BackgroundColor = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer))
        GpHatch7.ForegroundColor = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer))
        GpBrush7.Hatch = GpHatch7
        GpBrush7.InterpolationColors = GpInterpolationColors7
        ControlFont3.Brush = GpBrush7
        ControlFont3.InternalData = CType(resources.GetObject("ControlFont3.InternalData"), Vcl.VclBinaryData)
        GpBlend8.Blends = GpBlends8
        GpBlendShape8.Focus = 0.5!
        GpBlendShape8.Scale = 1.0!
        GpBlend8.Shape = GpBlendShape8
        GpBrush8.Blend = GpBlend8
        GpBrush8.Color = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer))
        GpCenterColor8.Color = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer))
        GpCenterPoint8.X = 0!
        GpCenterPoint8.Y = 0!
        GpCenterColor8.Point = GpCenterPoint8
        GpGradient8.CenterColor = GpCenterColor8
        GpGradient8.Colors = GpColors8
        GpGradient8.Path = GpPoints8
        GpBrush8.Gradient = GpGradient8
        GpHatch8.BackgroundColor = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer))
        GpHatch8.ForegroundColor = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer))
        GpBrush8.Hatch = GpHatch8
        GpBrush8.InterpolationColors = GpInterpolationColors8
        GpOptionalMultiPen3.Brush = GpBrush8
        GpOptionalMultiPen3.Compound = GpPenCompound3
        GpDashStyle3.CustomDash = GpCustomDash3
        GpDashStyle3.Offset = 0!
        GpOptionalMultiPen3.DashStyle = GpDashStyle3
        GpOptionalMultiPen3.Enabled = False
        GpOptionalMultiPen3.MiterLimit = 0!
        GpOptionalMultiPen3.Width = 1.0!
        ControlFont3.Pen = GpOptionalMultiPen3
        ElementSize11.Value = 0.065!
        ControlFont3.Size = ElementSize11
        InstrumentTicksText2.Font = ControlFont3
        ElementSize12.Value = 0.35!
        InstrumentTicksText2.Position = ElementSize12
        InstrumentTicksText2.Visible = False
        InstrumentLabeledTicks1.Labels = InstrumentTicksText2
        ElementSize13.Value = 0.15!
        InstrumentLabeledTicks1.Length = ElementSize13
        ElementSize14.Value = 0.005!
        InstrumentLabeledTicks1.Thickness = ElementSize14
        InstrumentLabeledTicks1.Visible = True
        BasicGaugeScale1.MinorTicks = InstrumentLabeledTicks1
        ElementSize15.Value = 0.15!
        BasicGaugeScale1.Position = ElementSize15
        ScalePrecision1.FixedPrecision = False
        ScalePrecision1.NumberDigits = CType(2UI, UInteger)
        BasicGaugeScale1.Precision = ScalePrecision1
        Me.Thermometer1.Scale = BasicGaugeScale1
        Me.Thermometer1.Size = New System.Drawing.Size(126, 412)
        Me.Thermometer1.TabIndex = 3
        Me.Thermometer1.Text = "Thermometer1"
        Me.Thermometer1.Value = 0R
        '
        'SegmentClock1
        '
        Me.SegmentClock1.Color = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer))
        ElementSize16.Value = 0.1!
        DecimalPointOffset1.Bottom = ElementSize16
        ElementSize17.Value = 0.04!
        DecimalPointOffset1.Right = ElementSize17
        DecimalPointSegment1.Offset = DecimalPointOffset1
        ElementSize18.Value = 0.13!
        DecimalPointSegment1.Size = ElementSize18
        DecimalPointSegment1.Visible = False
        Me.SegmentClock1.DecimalPoint = DecimalPointSegment1
        ElementSize19.Value = 0.1!
        SegmentIndents1.Bottom = ElementSize19
        ElementSize20.Value = 0.1!
        SegmentIndents1.Left = ElementSize20
        ElementSize21.Value = 0.1!
        SegmentIndents1.Right = ElementSize21
        ElementSize22.Value = 0.1!
        SegmentIndents1.Top = ElementSize22
        Me.SegmentClock1.Indents = SegmentIndents1
        Me.SegmentClock1.InputPin = SinkPin2
        Me.SegmentClock1.Location = New System.Drawing.Point(470, 12)
        Me.SegmentClock1.Name = "SegmentClock1"
        Rotation2.Angle = 0!
        Rotation2.Width = 0.7!
        Me.SegmentClock1.Rotation = Rotation2
        ElementSize23.Value = 0.1!
        PointOffset1.Left = ElementSize23
        ElementSize24.Value = 0.7!
        PointOffset1.Top = ElementSize24
        DigitalAmPmSection1.AmPosition = PointOffset1
        SegmentFont1.InternalData = CType(resources.GetObject("SegmentFont1.InternalData"), Vcl.VclBinaryData)
        ElementSize25.Value = 0.3!
        SegmentFont1.Size = ElementSize25
        DigitalAmPmSection1.Font = SegmentFont1
        ElementSize26.Value = 0.1!
        PointOffset2.Left = ElementSize26
        ElementSize27.Value = 0.2!
        PointOffset2.Top = ElementSize27
        DigitalAmPmSection1.PmPosition = PointOffset2
        DigitalAmPmSection1.Visible = False
        ElementSize28.Value = 0.6!
        DigitalAmPmSection1.Width = ElementSize28
        DigitalClockSections1.AmPm = DigitalAmPmSection1
        DigitalHourSection1.Visible = True
        DigitalClockSections1.Hours = DigitalHourSection1
        MillisecondsClockSection1.NumberDigits = CType(3UI, UInteger)
        SegmentClockSeparator1.Visible = True
        ElementSize29.Value = 0.3!
        SegmentClockSeparator1.Width = ElementSize29
        MillisecondsClockSection1.Separator = SegmentClockSeparator1
        DigitalClockSections1.Milliseconds = MillisecondsClockSection1
        SegmentClockSeparator2.Visible = True
        ElementSize30.Value = 0.3!
        SegmentClockSeparator2.Width = ElementSize30
        DigitalClockSection1.Separator = SegmentClockSeparator2
        DigitalClockSection1.Visible = True
        DigitalClockSections1.Minutes = DigitalClockSection1
        SegmentClockSeparator3.Visible = True
        ElementSize31.Value = 0.3!
        SegmentClockSeparator3.Width = ElementSize31
        DigitalClockSection2.Separator = SegmentClockSeparator3
        DigitalClockSection2.Visible = True
        DigitalClockSections1.Seconds = DigitalClockSection2
        Me.SegmentClock1.Sections = DigitalClockSections1
        Segment1.CenterColor = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer), CType(CType(0, Byte), Integer))
        Segment1.Color = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(255, Byte), Integer), CType(CType(0, Byte), Integer))
        ElementSize32.Value = 0.01!
        Segment1.Gap = ElementSize32
        Segment1.InactiveColor = InactiveColor1
        ElementSize33.Value = 0.13!
        Segment1.Width = ElementSize33
        Me.SegmentClock1.Segments = Segment1
        Me.SegmentClock1.Size = New System.Drawing.Size(162, 40)
        Me.SegmentClock1.TabIndex = 4
        Me.SegmentClock1.Text = "SegmentClock1"
        Me.SegmentClock1.Value = New Date(1899, 12, 30, 0, 0, 0, 0)
        '
        'SegmentClock2
        '
        Me.SegmentClock2.Color = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer), CType(CType(0, Byte), Integer))
        ElementSize34.Value = 0.1!
        DecimalPointOffset2.Bottom = ElementSize34
        ElementSize35.Value = 0.04!
        DecimalPointOffset2.Right = ElementSize35
        DecimalPointSegment2.Offset = DecimalPointOffset2
        ElementSize36.Value = 0.13!
        DecimalPointSegment2.Size = ElementSize36
        DecimalPointSegment2.Visible = False
        Me.SegmentClock2.DecimalPoint = DecimalPointSegment2
        ElementSize37.Value = 0.1!
        SegmentIndents2.Bottom = ElementSize37
        ElementSize38.Value = 0.1!
        SegmentIndents2.Left = ElementSize38
        ElementSize39.Value = 0.1!
        SegmentIndents2.Right = ElementSize39
        ElementSize40.Value = 0.1!
        SegmentIndents2.Top = ElementSize40
        Me.SegmentClock2.Indents = SegmentIndents2
        Me.SegmentClock2.InputPin = SinkPin3
        Me.SegmentClock2.Location = New System.Drawing.Point(470, 368)
        Me.SegmentClock2.Name = "SegmentClock2"
        Rotation3.Angle = 0!
        Rotation3.Width = 0.7!
        Me.SegmentClock2.Rotation = Rotation3
        ElementSize41.Value = 0.1!
        PointOffset3.Left = ElementSize41
        ElementSize42.Value = 0.7!
        PointOffset3.Top = ElementSize42
        DigitalAmPmSection2.AmPosition = PointOffset3
        SegmentFont2.InternalData = CType(resources.GetObject("SegmentFont2.InternalData"), Vcl.VclBinaryData)
        ElementSize43.Value = 0.3!
        SegmentFont2.Size = ElementSize43
        DigitalAmPmSection2.Font = SegmentFont2
        ElementSize44.Value = 0.1!
        PointOffset4.Left = ElementSize44
        ElementSize45.Value = 0.2!
        PointOffset4.Top = ElementSize45
        DigitalAmPmSection2.PmPosition = PointOffset4
        DigitalAmPmSection2.Visible = False
        ElementSize46.Value = 0.6!
        DigitalAmPmSection2.Width = ElementSize46
        DigitalClockSections2.AmPm = DigitalAmPmSection2
        DigitalHourSection2.Visible = True
        DigitalClockSections2.Hours = DigitalHourSection2
        MillisecondsClockSection2.NumberDigits = CType(3UI, UInteger)
        SegmentClockSeparator4.Visible = True
        ElementSize47.Value = 0.3!
        SegmentClockSeparator4.Width = ElementSize47
        MillisecondsClockSection2.Separator = SegmentClockSeparator4
        DigitalClockSections2.Milliseconds = MillisecondsClockSection2
        SegmentClockSeparator5.Visible = True
        ElementSize48.Value = 0.3!
        SegmentClockSeparator5.Width = ElementSize48
        DigitalClockSection3.Separator = SegmentClockSeparator5
        DigitalClockSection3.Visible = True
        DigitalClockSections2.Minutes = DigitalClockSection3
        SegmentClockSeparator6.Visible = True
        ElementSize49.Value = 0.3!
        SegmentClockSeparator6.Width = ElementSize49
        DigitalClockSection4.Separator = SegmentClockSeparator6
        DigitalClockSection4.Visible = True
        DigitalClockSections2.Seconds = DigitalClockSection4
        Me.SegmentClock2.Sections = DigitalClockSections2
        Segment2.CenterColor = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer), CType(CType(0, Byte), Integer))
        Segment2.Color = System.Drawing.Color.FromArgb(CType(CType(0, Byte), Integer), CType(CType(255, Byte), Integer), CType(CType(0, Byte), Integer))
        ElementSize50.Value = 0.01!
        Segment2.Gap = ElementSize50
        Segment2.InactiveColor = InactiveColor2
        ElementSize51.Value = 0.13!
        Segment2.Width = ElementSize51
        Me.SegmentClock2.Segments = Segment2
        Me.SegmentClock2.Size = New System.Drawing.Size(162, 40)
        Me.SegmentClock2.TabIndex = 5
        Me.SegmentClock2.Text = "SegmentClock2"
        Me.SegmentClock2.Value = New Date(1899, 12, 30, 0, 0, 0, 0)
        '
        'Form2
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.ClientSize = New System.Drawing.Size(660, 450)
        Me.Controls.Add(Me.SegmentClock2)
        Me.Controls.Add(Me.SegmentClock1)
        Me.Controls.Add(Me.Thermometer1)
        Me.Controls.Add(Me.Button2)
        Me.Controls.Add(Me.Button1)
        Me.Controls.Add(Me.Image1)
        Me.Name = "Form2"
        Me.Text = "Form2"
        CType(Me.Image1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.Thermometer1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.SegmentClock1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.SegmentClock2, System.ComponentModel.ISupportInitialize).EndInit()
        Me.ResumeLayout(False)

    End Sub

    Friend WithEvents Image1 As Mitov.UserLab.Image
    Friend WithEvents Button1 As Button
    Friend WithEvents Button2 As Button
    Friend WithEvents Thermometer1 As Mitov.InstrumentLab.Thermometer
    Friend WithEvents SegmentClock1 As Mitov.InstrumentLab.SegmentClock
    Friend WithEvents SegmentClock2 As Mitov.InstrumentLab.SegmentClock
End Class
